mkdir -p ../../../../ALL_v57_sys
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/Data.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/DataMain.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/Diboson.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/DibosonMassiveCB.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/GammaJet.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/GAMMAMassiveCB.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/GAMMAMassiveCB_TRUTH_filtered.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/GAMMAMassiveCB_TRUTH_filtered.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/GG_direct.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/GG_direct.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/GG_direct_mc15b.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/GG_direct_mc15b.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/GG_onestepCC.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/GG_onestepCC.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/QCD.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/QCD.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/SM_GG_N2.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/SM_GG_N2.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/SS_direct.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/SS_direct.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/SS_direct_mc15b.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/SS_direct_mc15b.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/Top.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/Top.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/TopPowhegHerwigpp.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/TopPowhegHerwigpp.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/TopPowhegPythia8.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/TopPowhegPythia8.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/TopaMcAtNloHerwigpp.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/TopaMcAtNloHerwigpp.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/ZMadgraphPythia8.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/ZMadgraphPythia8.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/Zjets.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/ZMassiveCB.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/WMadgraphPythia8.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/WMadgraphPythia8.root
./MakeSystematicsTree.x -ofile=../../../../ALL_v57_sys/Wjets.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v57/WMassiveCB.root
