mkdir -p ../../../../v53_Anum
mkdir -p ../../../../v53_Anum/BKG
./MakeZeroLeptonTree.x -ofile=../../../../v53_Anum/BKG/Top.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v53_Anum/Top.root
./MakeZeroLeptonTree.x -ofile=../../../../v53_Anum/BKG/Diboson.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v53_Anum/DibosonMassiveCB.root
./MakeZeroLeptonTree.x -ofile=../../../../v53_Anum/BKG/Wjets.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v53_Anum/WMassiveCB.root
./MakeZeroLeptonTree.x -ofile=../../../../v53_Anum/BKG/Zjets.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v53_Anum/ZMassiveCB.root
./MakeZeroLeptonTree.x -ofile=../../../../v53_Anum/GammaJet.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v53_Anum/GAMMAMassiveCB.root
./MakeZeroLeptonTree.x -ofile=../../../../v53_Anum/Data.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v53_Anum/DataMain.root
./MakeZeroLeptonTree.x -ofile=../../../../v53_Anum/GG_direct.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v53_Anum/GG_direct.root
./MakeZeroLeptonTree.x -ofile=../../../../v53_Anum/SS_direct.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v53_Anum/SS_direct.root
./MakeZeroLeptonTree.x -ofile=../../../../v53_Anum/GG_onestepCC.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v53_Anum/GG_onestepCC.root
./MakeZeroLeptonTree.x -ofile=../../../../v53_Anum/BKG/QCD.root -ifile=/Users/crogan/Dropbox/SAMPLES/ZeroLeptonRun2/v53_Anum/QCD.root
